"""
English knowledge-card corpus for the NanoLM NLP model.

Each card is one atomic English knowledge fact. The `keywords` list is the
hashable, discriminative content — it is tokenized into a 32,768-bit HLLSet
and stored under a `c:nlp:<id>` key in the hllset-next lattice. The `question`
and `answer` fields are the human-readable materialization returned to the
user.

Card shape (spec §6.2):
    {id, question, answer, domain, intent, keywords}

IMPORTANT: This is a small, curated seed corpus for architecture validation.
It is not a general-purpose knowledge base.
"""

ENGLISH_CARDS = [
    # ── Geography ────────────────────────────────────────────────────────
    {
        "id": "fact.capital.france",
        "question": "What is the capital of France?",
        "answer": "Paris is the capital of France.",
        "domain": "geography",
        "intent": "factual",
        "keywords": ["capital", "france"],
    },
    {
        "id": "fact.capital.india",
        "question": "What is the capital of India?",
        "answer": "New Delhi is the capital of India.",
        "domain": "geography",
        "intent": "factual",
        "keywords": ["capital", "india", "new", "delhi"],
    },
    {
        "id": "fact.capital.japan",
        "question": "What is the capital of Japan?",
        "answer": "Tokyo is the capital of Japan.",
        "domain": "geography",
        "intent": "factual",
        "keywords": ["capital", "japan", "tokyo"],
    },
    {
        "id": "fact.capital.uk",
        "question": "What is the capital of the United Kingdom?",
        "answer": "London is the capital of the United Kingdom.",
        "domain": "geography",
        "intent": "factual",
        "keywords": ["capital", "united", "kingdom", "london", "uk", "britain"],
    },
    {
        "id": "fact.currency.japan",
        "question": "What is the currency of Japan?",
        "answer": "The currency of Japan is the Japanese yen.",
        "domain": "geography",
        "intent": "factual",
        "keywords": ["currency", "japan", "yen"],
    },

    # ── Science ──────────────────────────────────────────────────────────
    {
        "id": "science.water.formula",
        "question": "What is the chemical formula of water?",
        "answer": "Water is H2O — two hydrogen atoms and one oxygen atom.",
        "domain": "science",
        "intent": "factual",
        "keywords": ["water", "formula", "h2o", "chemical"],
    },
    {
        "id": "science.light.speed",
        "question": "What is the speed of light?",
        "answer": "The speed of light in a vacuum is about 299,792,458 metres per second.",
        "domain": "science",
        "intent": "factual",
        "keywords": ["speed", "light", "vacuum"],
    },
    {
        "id": "science.gravity.newton",
        "question": "Who discovered gravity?",
        "answer": "Isaac Newton formulated the law of universal gravitation.",
        "domain": "science",
        "intent": "factual",
        "keywords": ["gravity", "newton", "isaac", "discover"],
    },

    # ── Technology ───────────────────────────────────────────────────────
    {
        "id": "tech.python.creator",
        "question": "Who created the Python programming language?",
        "answer": "Guido van Rossum created the Python programming language in 1991.",
        "domain": "technology",
        "intent": "factual",
        "keywords": ["python", "creator"],
    },
    {
        "id": "tech.quantum.what",
        "question": "What is quantum computing?",
        "answer": "Quantum computing uses qubits that can be in superposition, enabling certain calculations far faster than classical computers.",
        "domain": "technology",
        "intent": "factual",
        "keywords": ["quantum", "computing"],
    },
    {
        "id": "tech.quantum.qubit",
        "question": "What is a qubit?",
        "answer": "A qubit is the basic unit of quantum information; unlike a classical bit it can be 0 and 1 at the same time (superposition).",
        "domain": "technology",
        "intent": "factual",
        "keywords": ["qubit"],
    },
    {
        "id": "tech.http.status",
        "question": "What does HTTP 404 mean?",
        "answer": "HTTP 404 means the requested resource was not found on the server.",
        "domain": "technology",
        "intent": "factual",
        "keywords": ["http", "404", "not", "found"],
    },

    # ── General knowledge ────────────────────────────────────────────────
    {
        "id": "gen.earth.planets",
        "question": "How many planets are in the solar system?",
        "answer": "There are eight planets in the solar system: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune.",
        "domain": "general",
        "intent": "factual",
        "keywords": ["planets", "solar", "system", "eight"],
    },
    {
        "id": "gen.human.bones",
        "question": "How many bones are in the adult human body?",
        "answer": "An adult human body has 206 bones.",
        "domain": "general",
        "intent": "factual",
        "keywords": ["bones", "human", "body", "206", "adult"],
    },
    {
        "id": "gen.ocean.largest",
        "question": "What is the largest ocean on Earth?",
        "answer": "The Pacific Ocean is the largest ocean on Earth.",
        "domain": "general",
        "intent": "factual",
        "keywords": ["largest", "ocean", "pacific", "earth"],
    },

    # ── Subject definitions ("what is X?") ───────────────────────────────
    {
        "id": "def.history",
        "question": "What is history?",
        "answer": "History is the study of past events, particularly in human affairs.",
        "domain": "general",
        "intent": "factual",
        "keywords": ["history"],
        "details": "Historians gather evidence from documents, artifacts, and oral accounts to interpret how societies changed over time — covering periods, events, and influential figures.",
    },
    {
        "id": "def.science",
        "question": "What is science?",
        "answer": "Science is the systematic study of the natural world through observation, experiment, and reasoning.",
        "domain": "science",
        "intent": "factual",
        "keywords": ["science"],
        "details": "Science proceeds by forming hypotheses, testing them with experiments, and refining theories based on evidence — spanning fields like physics, chemistry, biology, and earth science.",
    },
    {
        "id": "def.geography",
        "question": "What is geography?",
        "answer": "Geography is the study of the Earth's lands, features, inhabitants, and phenomena.",
        "domain": "geography",
        "intent": "factual",
        "keywords": ["geography"],
        "details": "It is traditionally divided into physical geography (landforms, climate, ecosystems) and human geography (populations, cultures, economies, and how people shape places).",
    },
    {
        "id": "def.technology",
        "question": "What is technology?",
        "answer": "Technology is the application of scientific knowledge for practical purposes, especially in industry.",
        "domain": "technology",
        "intent": "factual",
        "keywords": ["technology"],
        "details": "It ranges from simple tools and machines to software and digital systems, and it continuously reshapes how people live, work, and communicate.",
    },
    {
        "id": "def.mathematics",
        "question": "What is mathematics?",
        "answer": "Mathematics is the abstract science of number, quantity, and space, studied through logic and symbols.",
        "domain": "science",
        "intent": "factual",
        "keywords": ["mathematics", "math"],
        "details": "Its main branches include arithmetic, algebra, geometry, and calculus, and it provides the language used by the sciences and engineering.",
    },
    {
        "id": "def.music",
        "question": "What is music?",
        "answer": "Music is the art of arranging sounds in time to produce a composition with melody, harmony, and rhythm.",
        "domain": "general",
        "intent": "factual",
        "keywords": ["music"],
        "details": "Its core elements are pitch, rhythm, dynamics, and timbre; it appears in virtually every culture as a form of art, communication, and ritual.",
    },
    {
        "id": "def.art",
        "question": "What is art?",
        "answer": "Art is the expression of human creativity and imagination, typically in visual forms such as painting or sculpture.",
        "domain": "general",
        "intent": "factual",
        "keywords": ["art"],
        "details": "It also includes literature, music, dance, and film, and it often aims to evoke emotion, convey ideas, or capture beauty.",
    },
    {
        "id": "def.biology",
        "question": "What is biology?",
        "answer": "Biology is the scientific study of living organisms and life processes.",
        "domain": "science",
        "intent": "factual",
        "keywords": ["biology"],
        "details": "It spans levels from molecules and cells to organisms and ecosystems, with major fields including genetics, evolution, anatomy, and ecology.",
    },
    {
        "id": "def.chemistry",
        "question": "What is chemistry?",
        "answer": "Chemistry is the science of the composition, structure, properties, and reactions of matter.",
        "domain": "science",
        "intent": "factual",
        "keywords": ["chemistry"],
        "details": "It studies atoms, molecules, and chemical bonds, and underpins fields such as biochemistry, materials science, and pharmacology.",
    },
    {
        "id": "def.physics",
        "question": "What is physics?",
        "answer": "Physics is the science of matter, energy, motion, and force, and their interactions.",
        "domain": "science",
        "intent": "factual",
        "keywords": ["physics"],
        "details": "It encompasses mechanics, thermodynamics, electromagnetism, and quantum theory, and seeks the fundamental laws that describe the universe.",
    },
    {
        "id": "def.economics",
        "question": "What is economics?",
        "answer": "Economics is the social science that studies how people produce, distribute, and consume goods and services.",
        "domain": "general",
        "intent": "factual",
        "keywords": ["economics", "economy"],
        "details": "It is divided into microeconomics (individual choices and markets) and macroeconomics (whole economies, growth, inflation, and unemployment).",
    },
    {
        "id": "def.television",
        "question": "What is television?",
        "answer": "Television (TV) is a medium for transmitting moving images and sound to screens, used for news, entertainment, and education.",
        "domain": "technology",
        "intent": "factual",
        "keywords": ["television"],
        "details": "First demonstrated in the 1920s, television evolved from black-and-white to color and then to digital, cable, satellite, and internet streaming — becoming one of the most influential mass media.",
    },
    {
        "id": "def.computer",
        "question": "What is a computer?",
        "answer": "A computer is an electronic device that processes data according to a program, performing calculations and logic at high speed.",
        "domain": "technology",
        "intent": "factual",
        "keywords": ["computer"],
        "details": "Computers range from tiny embedded chips to supercomputers, and consist of hardware (processor, memory, storage) and software that directs what they do.",
    },
    {
        "id": "def.internet",
        "question": "What is the internet?",
        "answer": "The internet is a worldwide network of interconnected computers that exchange data using standard protocols.",
        "domain": "technology",
        "intent": "factual",
        "keywords": ["internet"],
        "details": "It carries services such as the World Wide Web, email, and streaming, and grew out of research networks in the late 20th century to connect billions of devices.",
    },
    {
        "id": "def.smartphone",
        "question": "What is a smartphone?",
        "answer": "A smartphone is a mobile phone that combines calling with computing, a touchscreen, and internet access.",
        "domain": "technology",
        "intent": "factual",
        "keywords": ["smartphone"],
        "details": "Beyond calls, smartphones run apps for messaging, photography, navigation, and payments, making them pocket-sized computers.",
    },
    {
        "id": "def.movie",
        "question": "What is a movie?",
        "answer": "A movie (film) is a story or event recorded as a sequence of moving images, usually shown in a cinema or on a screen.",
        "domain": "general",
        "intent": "factual",
        "keywords": ["movie", "film"],
        "details": "Movies combine photography, editing, sound, and performance, and range from short clips to feature-length productions across many genres.",
    },
    {
        "id": "def.rhyme",
        "question": "What is rhyme?",
        "answer": "A rhyme is the repetition of similar sounds, usually the same ending sounds, in two or more words — as in \"cat\" and \"hat\" — most often used at the ends of lines in poems and songs.",
        "domain": "general",
        "intent": "factual",
        "keywords": ["rhyme"],
        "details": "Rhymes can be perfect (an exact vowel-and-consonant match, like \"day\"/\"play\") or slant (similar but not identical sounds). The pattern of end rhymes in a poem is called its rhyme scheme and is often labeled with letters, such as ABAB.",
    },
    {
        "id": "fact.animal.phyla",
        "question": "How many phyla are there in the animal kingdom?",
        "answer": "The animal kingdom is divided into about 35 phyla (nine of which are traditionally considered major), including Chordata, Arthropoda, and Mollusca.",
        "domain": "science",
        "intent": "factual",
        "keywords": ["phylum", "phyla", "animal", "kingdom"],
    },
    {
        "id": "def.reprise",
        "question": "What is a reprise?",
        "answer": "A reprise is a repetition or recurrence of something — in music, it is a repeated passage or a return to an earlier theme, and in entertainment it often means an actor returning to a familiar role.",
        "domain": "general",
        "intent": "factual",
        "keywords": ["reprise"],
        "details": "In music a reprise returns to a previously heard theme; in film, theater, or television it commonly means an actor revisiting a role they played before, as in \"reprising a role.\"",
    },
    {
        "id": "fact.hinduism.ram",
        "question": "Who is Ram?",
        "answer": "Ram (also spelled Rama) is a major deity in Hinduism, the seventh avatar of the god Vishnu, and the hero of the ancient Indian epic the Ramayana.",
        "domain": "general",
        "intent": "factual",
        "keywords": ["ram", "rama"],
    },
    {
        "id": "fact.gandhi",
        "question": "Who was Mahatma Gandhi?",
        "answer": "Mahatma Gandhi (Mohandas Karamchand Gandhi, 1869–1948) was the leader of India's non-violent independence movement against British rule.",
        "domain": "history",
        "intent": "factual",
        "keywords": ["gandhi"],
    },
    {
        "id": "def.phylum",
        "question": "What is a phylum?",
        "answer": "A phylum is a major level of biological classification, ranking below kingdom and above class; for example, Chordata is the phylum that includes all vertebrates.",
        "domain": "science",
        "intent": "factual",
        "keywords": ["phylum", "phyla"],
    },
    {
        "id": "def.meaning",
        "question": "What is meaning?",
        "answer": "Meaning is what a word, phrase, symbol, or action signifies or represents — its definition, sense, or intended message.",
        "domain": "general",
        "intent": "factual",
        "keywords": ["meaning"],
    },

    # ── Small talk / help (also handled by intent templates) ─────────────
    {
        "id": "smalltalk.howareyou",
        "question": "How are you?",
        "answer": "I am functioning well, thank you for asking. How can I help you today?",
        "domain": "smalltalk",
        "intent": "smalltalk",
        "keywords": ["how", "are", "you"],
    },
    {
        "id": "smalltalk.thanks",
        "question": "Thank you",
        "answer": "You are welcome! Feel free to ask me another question.",
        "domain": "smalltalk",
        "intent": "smalltalk",
        "keywords": ["thank", "thanks", "welcome"],
    },
    {
        "id": "help.whatcanyoudo",
        "question": "What can you do?",
        "answer": "I am NanoLM, a lattice-based English language model. I answer questions by retrieving relevant knowledge from an ingested corpus. Ask me about geography, science, or technology.",
        "domain": "help",
        "intent": "help",
        "keywords": ["what", "can", "you", "do", "help", "commands"],
    },
]
